### PR TITLE
Implementation of GitHug Actions

### PR DESCRIPTION
**Pull request by jlconlin**
This Pul Request add (really finalizes) the use of GitHub Actions. It adds a workflow that will test the code using gfortran version 8 in Release and Debug mode.

### CODE REVIEW

**Comment by nathangibson14** [comment]
Before I review this at all, I have to comment that "GitHug" is a fantastic typo.

**Comment by paulromano** [comment]
:laughing: Please don't change the title of the PR :hugs: :octocat:

**Comment by jlconlin** [comment]
> Before I review this at all, I have to comment that "GitHug" is a fantastic typo.

How do you know it is a typo? 😉

**Comment by whaeck** [comment]
There's not much to review here. Can I assume it will work so that I can get this going on my latest branch?

**Comment by jlconlin** [comment]
@whaeck You don't have to assume that it is working. You can look [here](https://github.com/njoy/NJOY2016/actions?query=workflow%3A%22Continuous+Integration%22) and get that warm feeling that knows that GitHub is **hugging** NJOY2016.

**Pull request merged**
