### PR TITLE
Fix/heatr nbt

### PR DESCRIPTION
**Pull request by whaeck**
Some evaluations use MF5 energy distribution data for reactions such as MT16, MT15, inelastic levels, etc. in which more than one interpolation ranges are used. Examples from ENDF/B-VIII.0 are Sn119 and Sn122 (there are more than just these, but these are the ones I looked at).

The integration routines did not extract the interpolation data from the right spot in the ENDF file. The tabbar subroutine (which calculates average outgoing neutron energy) and tabsqr subroutine (which calculates photon recoil) were corrected.

### CODE REVIEW

**Comment by JoffreyDorville** [comment]
Thanks for integrating this correction!

**Review by kahlerac — APPROVED** [review]
Code changes look good to me.

**Comment by whaeck** [comment]
@kahlerac You'll have to reapprove this since I had to fix a conflict on the release notes.

**Review by kahlerac — APPROVED** [review]
Re-approved

**Pull request merged**
