### PR TITLE
Fix/groupr li

### PR DESCRIPTION
**Pull request by whaeck**
The fix for the latest GROUPR issue. I looked through the tests, the changes appear to be limited to the 6th significant digit so looks like roundoff.

### CODE REVIEW

**Review by kahlerac — CHANGES_REQUESTED** [review]
The current lct=0 declaration in Subroutine getfle only works by accident.  A more general fix is to eliminate the local lct declaration and subsequent save lct declaration in Subroutine getmf6.  "lct" has already been declared as global and overlaying a local/save declaration seems to cause old, no longer relevant, data to override the current value of this variable.

**Comment by whaeck** [comment]
I expected this as soon as I found out that the lct variable was a global variable - and not a local one. Do you want to make these changes? We can discuss this in more detail during our next meeting.

**Review by kahlerac — COMMENTED** [review]
Undid the initial patch and implemented a more general correction.  Also tweaked the text describing the fix.

**Comment by whaeck** [comment]
Well, that was easy :-)

I'll have a look at the tests. I might just revert the test results first to see how this change impacts the tests.

**Comment by whaeck** [comment]
Closing this one in favour of #302

**Pull request closed without merging**
