### PR TITLE
Fix/tendl pn

### LINKED ISSUE #201: TENDL photonuclear processing issue for Ra226
An email was posted to the MCNP user forum concerning an issue with a photonuclear ACE file for Ra226 from TENDL 2019.

The length of the ACE file did not correspond to the length written to the xsdir entry, indicating an issue while printing the ACE file. When performing an ACER run for testing an existing ACE file, ACER crashes due to an expected end of file (again due to the ACE file being incomplete).

The following input and ENDF file illustrate the issue:
[input.txt](https://github.com/njoy/NJOY2016/files/6535009/input.txt)
[g-Ra226.tendl.txt](https://github.com/njoy/NJOY2016/files/6535010/g-Ra226.tendl.txt)

### PR DESCRIPTION
**Pull request by whaeck**
This fixes #201, see the issue for more information.

### CODE REVIEW

**Comment by kahlerac** [comment]
Hi Wim,
   On the road between Florida and South Carolina. It'll be later this week
before I can get to this.  Is that OK, or maybe someone else can step in if
you can't wait.
Skip

sent from my mobile

**Comment by whaeck** [comment]
No worries Skip. It can wait a few days ;-)

This one is also relatively simple (took longer to diagnose though).

**Review by kahlerac — APPROVED** [review]
Code changes seem reasonable ... good job tracking down these subtle errors.

**Comment by jchsublet** [comment]
Excellent job, it does also works for numerous targets from g-tendl-2019, now producing beautiful if not always physical ace check tapes, the one below with a reconr sequence

[Fe056chk.pdf](https://github.com/njoy/NJOY2016/files/6570666/Fe056chk.pdf)

**Comment by kahlerac** [comment]
Thanks for this additional check JCS.  I did the review/approval on
Saturday but it's a holiday in the US today.
Skip

sent from my mobile

**Comment by whaeck** [comment]
@kahlerac I updated the release notes, and set up a weekly schedule to run all tests from now on. No need to review these last changes. Once the tests have run, I'll merge and tag a release.

**Pull request merged**
